dvajs/dva

.gitignore
.travis.yml
examples/user-dashboard/src/entries/index.js
package.json
src/index.js
src/utils.js
test/app.model-test.js
test/app.start-test.js
test/basic-test.js

Close #7 
---
`dva()`
`app.start()`
`app.model()`
other

Implement new api

---

src/utils.js

使用`document.getElementById()`等方法，获取不到DOM元素时会返回null。此时报错行在https://github.com/sorrycc/dva/blob/master/src/utils.js#L22 ，错误内容为`Uncaught TypeError: Cannot read property 'nodeType' of null`。表意不明。
参考源码：https://github.com/sorrycc/dva/blob/master/src/index.js#L57 。可以知道预期报错内容为：`Container must be DOMElement.`。与预期不符。
修复了这个问题之后，我觉得`check`函数传入的`error`参数应该调整成一个函数，这样可以获取到传入的`value`，错误信息能够调整为：`Container must be DOMElement, but got ${typeof value}`

fix:app.start的container传入null时报错不明确

---

Makefile
examples/count-undo/index.js
src/index.js
src/plugin.js
test/app.use-test.js
test/plugin-test.js

通过 `onReducer` 支持全局的 reducerEnhancer，其中一个案例是支持 redux-undo。
比如：
```javascript
import undoable from 'redux-undo';
const app = dva({
onReducer: undoable,
});
...
```
但是这样写顶层的 `routing` 就没了，所以需要把 `routing` 重新移出来。
```javascript
import undoable from 'redux-undo';
const app = dva({
onReducer: reducer => {
return (state, action) => {
const undoOpts = {};
const newState = undoable(reducer, undoOpts)(state, action);
return { ...newState, routing: newState.present.routing };
};
},
});
```

add onReducer hook to support reducer enhancer

---

src/index.js

Close #54 
---
match 是为了从 router 里获取 params，之后 params 改为通过 path-to-regexp 获取，参考：dvajs/dva-hackernews@3314c7c

feat: remove router match from history

---

README.md
package.json
src/createDva.js
src/plugin.js
test/effects-test.js

比如：实现 effect 执行时，自动切换 loading 状态。
定义插件：
```javascript
const SHOW = '@@LOADING/SHOW';
const HIDE = '@@LOADING/HIDE';
function autoLoading() {
return {
extraReducers: {
loading(state, action) {
switch (action.type) {
case SHOW:
return true;
case HIDE:
return false;
default:
return false;
}
},
},
onEffect(effect, { put }, model) {
modelNamespace = model.namespace;
return function*() {
count = count * 2;
yield put({ type: SHOW });
yield effect();
yield put({ type: HIDE });
};
},
};
}
```
使用：
```javascript
const app = dva();
app.use(autoLoading());
```
然后在 `state.loading` 就可以自动切换状态了。

Add on effect hook

---

src/createDva.js
test/effects-test.js

这样，我们就能捕获 effect 级的 loading 状态了。
Related issue:
https://github.com/dvajs/dva-loading/issues/1

Add action type to onEffect

---

examples/user-dashboard/src/components/Users/UserModal.jsx

修复 user-dashboard 从第二页开始，点击编辑用户，什么信息都不修改，点击确定会提示“年龄未填写”。Close #196

fix user-dashboard edit age  bug

---

examples/user-dashboard/package.json
examples/user-dashboard/src/models/users.js
examples/user-dashboard/src/routes/Users.jsx

1.  ```npm run lint ``` 报错
2.  关键字搜索时没有把相应的字段带到 url 里。
1. 安装```eslint-config-rackt```
2. 当```payload```为```{ }```时给初始值

example user-dashboard 优化

---

index.d.ts

Since JSX is declared as a global namespace[1], don't need import React explicitly.
1. https://github.com/DefinitelyTyped/DefinitelyTyped/blob/f4f0bef0e10b719484c1327166f96fd5bd758db7/react/index.d.ts#L2629-L2630
\cc @pvtyuan

Remove React import

---

packages/dva-example-user-dashboard/src/router.js
packages/dva/src/dynamic.js

https://github.com/dvajs/dva/blob/master/packages/dva-example-user-dashboard/src/router.js#L11 
```js
const Users = dynamic({
app,
models: [
import('./models/users'),
],
component: import('./routes/Users'),
});
```
这种 `dynamic ` 写法，在加载router.js的时候，models和component都会被加载，事实上貌似没有做到dynamic？此处应该传入function，在asyncComponent()里去resolve需要动态加载的模块
例如
```js
const Users = dynamic({
app,
models: () => [
import('./models/users'),
],
component: () => import('./routes/Users'),
});
```
另外 实际使用时，可能需要在 `app.model(model)` 前对model做些处理，所以dynamic可以传入自定义的app.model方法，使用更灵活一些，例如
```js
const mounter = app.model
// or
// const mounter = model => app.model(doSomething(model))
const Users = dynamic({
mounter,
models: () => [
import('./models/users'),
],
component: () => import('./routes/Users'),
});
```

fix dynamic

---

packages/dva-core/src/getSaga.js
packages/dva-core/src/index.js
packages/dva-core/test/optsAndHooks-test.js

feat(dva-core): support e.preventDefault() in onError to prevent reject

---

packages/dva/package.json

```
npm WARN react-router-redux@5.0.0-alpha.6 requires a peer of react@^15 but none was installed.
```
https://github.com/ant-design/ant-design-pro/issues/137#issuecomment-342715104

upgrade react-router-redux

---

packages/dva-example-user-dashboard/src/components/Users/UserModal.js

Form horizontal 属性 2.8 之后已经废弃， 改为layout

antd Form 更新布局属性 消除控制台警告

---

packages/dva-core/src/createStore.js

https://github.com/zalmoxisus/redux-devtools-extension
```jsx
import { createStore, applyMiddleware, compose } from 'redux';
+ const composeEnhancers = window.__REDUX_DEVTOOLS_EXTENSION_COMPOSE__ || compose;
+ const store = createStore(reducer, /* preloadedState, */ composeEnhancers(
- const store = createStore(reducer, /* preloadedState, */ compose(
applyMiddleware(...middleware)
));
```

fix: redux devtools maybe effect other enhancers.

---

packages/dva/src/index.js

fix #1563, see https://github.com/dvajs/dva/pull/1589#issuecomment-378110269

show root displayName

---

packages/dva-core/src/getSaga.js
packages/dva-core/src/index.js
packages/dva-core/test/effects.test.js

To enhance ``hook: onError`` with extension arguments
**log error info**
```
const app = dva({
onError(err, dispatch, { key, effectArgs }) {
dispatch({
type: 'error/log',
payload: {
key,
effectArgs,
}
})
}
})
```

feat: Add extension args to onError hook

---

packages/dva-core/src/getSaga.js
packages/dva-core/test/effects.test.js

``put.resolve`` is a native effect API of redux-saga. This PR will patch this behavior to the effect of dva.
> In order to wait for the returned Promise, use the variant put.resolve(...) which will wait until the Promise resolve (or rejects) before resuming.
- Dispatch other effects in order
```
const model = {
namespace: '@user',
...,
effects: {
*fetchList({ payload }, { call }) {
const list = yield call(service.fetchList, payload)
yield put({ type: 'dumpList', payload: list })
},
*delete({ payload }, { call }) {
yield call(service.delete, payload)
},
*deleteAndReload({ payload }, { put }) {
yield put.resolve({ type: 'delete', payload })
yield put({ type: 'fetchList' })
}
}
}
```

feat: Support `put.sync` to wait the effect to resolve

---

packages/dva/index.d.ts

change the Action to AnyAction！
export interface AnyAction extends Action {
// Allows any extra properties to be defined in an action.
[extraProps: string]: any;
}

 Action does not support extra attributes

---

packages/dva-no-router/package.json

include missed *.d.ts files for dva-no-router in package.json to support TypeScript.
after I installing the dav-no-router (1.1.4) package by `npm install dva-no-router` or `yarn add dva-no-router`, I found there are no *.d.ts files included in the package while they are included in the source code.
according issue #1415 , I think it is because the *.d.ts are not included in the package.json.
cc @sorrycc

chore: include missed *.d.ts files for dva-no-router in package.json

---

packages/dva-core/src/getSaga.js

when the first parameter of function take is typeof array, in the callback of type.map call, at line 132, the first parameter of prefixType, passing variable type (is array, not a take pattern) instead of t (array item, take pattern) causes incorrect result.
当take的第一个参数是数组时，在type.map调用的回调函数中，在132行，prefixType的第一个参数，传递变量type（是数组，而不是take模式）而不是t（是数组项，take模式）会导致错误结果。

fix: take(Array) don't work property

---

packages/dva-core/src/index.js

there's no need to pass asyncReducer from argument

fix: unnecessary param of createReducer

---

packages/dva-no-router/index.d.ts
packages/dva/index.d.ts

hey @sorrycc ,
today I started to use subscriptions feature in dva-no-router, then the TS compiler tells me the Model has no subscriptions filed, I reviewed the index.d.ts in dva-no-router source code, it is true that there is no subscriptions filed.
so I just copied the latest index.d.ts from dva folder to dva-no-router folder, although we can delete some contents that dva-no-router doesn't need, but I think it is better to keep them the same, because I think we can update the build files later to auto copy index.d.ts from dva to dva-no-router if it is changed.
I also update the index.d.ts code style to unify the ending symbol for interface fields.

Update index.d.ts for dva-no-router

---

packages/dva-loading/package.json
packages/dva-loading/test/core.test.js

For `dva-loading`, it only requires `dva-core` to work. 
This PR changes peerDeps of `dva-loading` from `dva` to `dva-core`, which makes no peerDeps warning when `dva-core` works together with `dva-loading`.

change dva-loading peerDeps from dva to dva-core

---

packages/dva-no-router/package.json
packages/dva-react-router-3/package.json
packages/dva/package.json

fix: lock react-redux to 5.0.7

---

packages/dva-core/src/createStore.js

- 打开 `Redux`面板`trace`的开关,保留默认`10`条记录
Checklist
Description of change
`dva-core/src/createStore.js`
**before**
```javascript
const composeEnhancers =
process.env.NODE_ENV !== "production" &&
window.__REDUX_DEVTOOLS_EXTENSION_COMPOSE__
? window.__REDUX_DEVTOOLS_EXTENSION_COMPOSE__
: compose;
const enhancers = [applyMiddleware(...middlewares), ...extraEnhancers];
```
**after**
```javascript
const composeEnhancers =
process.env.NODE_ENV !== "production" &&
window.__REDUX_DEVTOOLS_EXTENSION_COMPOSE__
? window.__REDUX_DEVTOOLS_EXTENSION_COMPOSE__({ trace: true,maxAge:30 })
: compose;
const enhancers = [applyMiddleware(...middlewares), ...extraEnhancers];
```
首先`dva`非常好用
但是在现在开发的项目中`model`定义超过**100**个,由不同的开发人员进行开发，在调度`model`上各不同，调试变得略微麻烦，在找寻解决方法时发现`redux`有提供*调用追踪*，并在项目中使用，对于项目中追踪调度和调试还有有效率上的改变，所以 …

feat: open redux-devtool trace history

---

packages/dva/package.json
packages/dva/src/index.js
packages/dva/test/index.e2e.js
packages/dva/yarn.lock

feat: export useDispatch, useSelector and useStore from react-redux@7.1

---

packages/dva/index.d.ts
packages/dva/package.json

https://github.com/dvajs/dva/issues/2133
补充了  `d.ts` 里的 `useSelector` 等 API.
`interface` 类的目前只 export 了 `DispatchProp`，这个比较常用。`@types/react-redux` 暴露的 `interfaces` 太多，就没有一一处理。

deps: use typings exported from `@types/react-redux`

---

packages/dva/warnAboutDeprecatedCJSRequire.js

fix: es5 compatible with warnAboutDeprecatedCJSRequire.js

---

packages/dva/index.d.ts
packages/dva/src/index.js

feat: export bindActionCreators

---

docs/API.md
docs/api/README.md
packages/dva-core/src/getSaga.js
packages/dva-core/test/effects.test.js

- 添加新的effect 类型 `poll`，用来处理轮询逻辑
- add new effect type `poll`
```js
effects: {
pollAdd: [
function*(_, { put }) {
yield put({ type: 'add', payload: 1 });
},
{ type: 'poll', delay: 1000 },
],
},
// start polling
dispatch({ type: 'count/pollAdd-start' });
// stop polling
dispatch({ type: 'count/pollAdd-stop' })
```

feat: add poll effect type

---

package.json
packages/dva/package.json
packages/dva/src/index.js
packages/dva/test/index.e2e.js

- close https://github.com/umijs/umi/issues/2693

fix: history listener subscription execute multiple times

---

README.md

chore: add circleci

---

packages/dva-core/test/effects.test.js
packages/dva/src/index.js

- close https://github.com/dvajs/dva/issues/2220
- close #2130

fix: route push problem with subscription in prod mode

---

packages/dva-core/src/prefixNamespace.js

fix: qiankun remount for array type reducers
Using the mutate array method to prefix namespace will cause reducers' prefix keep growing on each remount in micro-frontend env.

fix: qiankun remount dva model

---

packages/dva/src/index.js

chore: add __isDvaPatch args for the initial history listen handler call
